### ISSUE TITLE
Google auth

### ISSUE THREAD

**Issue by oguh43** [vascYT/vshop-mobile#4]
**Describe the bug**
Can't login with a google type riot games account.
**To Reproduce**
1. Go to 'app'
2. Click on 'login'
3. See error/ fail to authentificate

**Expected behavior**
Login and use the app.

**Smartphone (please complete the following information):**
 - Device: samsung a72
 - OS: android 12

**Additional context**
Please for the love of god make the password field not auto capitalise :(

**Comment by vascYT** [comment]
I'm sorry but this is not a bug. VShop will probably never support Google login. Therefore, you are required to use your riot games login credentials.
