### ISSUE TITLE
Another bug?

### ISSUE THREAD

**Issue by faiz36** [vascYT/vshop-mobile#6]
I login at VShop but logged error like this
![Screenshot_20220406-081502_VShop.jpg](https://user-images.githubusercontent.com/79878012/161866157-6e781325-0351-4ab3-9089-983d8dad9d82.jpg)

**Comment by vascYT** [comment]
Good day,
that's not a bug. There are too many users so that Riot Games blocks our request. I am working on a fix. I'm really sorry about that. There were a total of 158.66k requests in the last 24 hours.

**Comment by vascYT** [comment]
I've shut down the server so that my server doesn't spam riot games with requests. So now you'll be stuck in a loading screen when trying to log in

**Comment by vascYT** [comment]
I've opened an issue in the vshop-backend repository: https://github.com/vascYT/vshop-backend/issues/

**Comment by faiz36** [comment]
okay (:

**Comment by vascYT** [comment]
The issue has been resolved
